service: aws-php-api

provider:
  name: aws
  runtime: provided
  region: ${opt:region, 'eu-central-1'}

plugins:
  - ./vendor/bref/bref

package:
  exclude:
    - .gitignore
    - composer.json
    - composer.lock
    - Makefile
    - README.md
    - test.php

functions:
  login:
    handler: login.php
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - http:
          path: api/login
          method: post
          cors: true

  auth:
    handler: auth.php
    layers:
      - ${bref:layer.php-74}

  public_endpoint:
    handler: public.php
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - http:
          path: api/public
          method: get
          cors: true

  private_endpoint:
    handler: private.php
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - http:
          path: api/private
          method: get
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token